### ISSUE TITLE
Step 3 Config File

### ISSUE THREAD

**Issue by CyberNinjaX** [innovyze/Open-Source-Support#17]
When loading Step 3 Config, no import fields were filled out for the manhole hydraulics. 

![image](https://github.com/innovyze/Open-Source-Support/assets/123211979/7e5ce328-e6b4-4e87-b475-e74afb94f8b7)

Thanks

**Comment by dfmore** [comment]
Hi @CyberNinjaX and apologies for the late reply. We don't generally monitor GitHub for support queries. Could you give us more detail on the workflow? If you could raise a case with [support@innovyze.com](url) we'd be happy to forward this to the appropriate member of staff. Thanks!

**Comment by dickinsonre** [comment]
Let me check that @CyberNinjaX - this is for InfoSewer

**Comment by kmaschmann** [comment]
The InfoSewer to ICM configuration files have been reviewed and updated as needed, including this step. Thanks!
