### ISSUE TITLE
Not an issue, but an improvement for Chamber and Shaft plan area

### ISSUE THREAD

**Issue by CyberNinjaX** [innovyze/Open-Source-Support#18]
This is just a suggestion. The file MHHYD.csv has diameter of manhole, so we can calculate the diameter by adding a column in the csv and use the ODIC to the Chamber plan area and Shaft plan area. This alleviate the need of assuming all of them are 4 ft manholes and the need for the SQL_InfoSewer_Manhole_Area.

**Comment by dfmore** [comment]
Hi @CyberNinjaX , could you point us to the link concerning the script you are using? Thanks

**Comment by dickinsonre** [comment]
HI I do have a SQL for doing this and we also have a conversion between diameter and area in ICM InfoWorks from InfoSewer  Manholes in InfoSewer are always 4 for the most part
