### ISSUE TITLE
How to expand selection from Pipe to Pipe clean?

### ISSUE THREAD

**Issue by PieterjanDG** [innovyze/Open-Source-Support#19]
In SQL, how to expand selection from Pipe to Pipe clean?

**Comment by PieterjanDG** [comment]
Or in Ruby?

**Comment by Krzysztof-T** [comment]
Hi @PieterjanDG, apologies for the late reply. We don't monitor GitHub for support queries. InfoCare supported customers can raise a case with support@innovyze.com and we'd be happy to forward this to the appropriate member of the team. Thanks!
