### ISSUE TITLE
New Ruby Documentation

### ISSUE THREAD

**Issue by DaveFace** [innovyze/Open-Source-Support#21]
As part of the 2025.0 release of InfoWorks WS Pro and InfoWorks ICM, the Ruby documentation which used to be provided as a PDF is now part of the official help pages.

[Link to WS Pro](https://help.autodesk.com/view/IWWSPRO/2025/ENU/) / [Link to ICM](https://help.autodesk.com/view/IWICMS/2025/ENU/). For the time-being the original documentation is still available [from this page](https://help.autodesk.com/view/IWWSPRO/2025/ENU/?guid=GUID-D9D60C18-817C-42D2-88C9-1C21F78CF18A).

It has been rewritten from scratch to provide clearer and more accurate information on the available API methods, and unlike the previous documentation which was shared between the products, each help page will only contain methods and options relevant to that product (ICM includes both ICM and InfoAsset Manager).

As this is the first release, there may be omissions or mistakes, so this issue will remain open for a while to capture any comments you may have. Of course you can also contact us via the usual support methods.

**Comment by DaveFace** [comment]
@sancarn tagging you as this is not strictly a continuation of the work we were doing last year (this was started from scratch) but is essentially the end result of wanting to make the documentation more useful

**Comment by DaveFace** [comment]
1. Not officially, I'm not sure if we have a means to support contributions at the moment. Though the Autodesk documentation is now under a specific license (CC BY-NC-SA 3.0).
2. The new documentation was generated from the source, so for the most part any methods that remain undocumented are intentional because they're not intended for general use (e.g. they are only supposed to work in limited cases), but more might be documented in future since ideally if the functionality exists, it should be usable

**Comment by sancarn** [comment]
> if the functionality exists, it should be usable

Indeed and if there is no functionality there, the method likely shouldn't exist at all!
