### ISSUE TITLE
InfoWater Pro Python - Can't get reservoir results

### ISSUE THREAD

**Issue by rickscr** [innovyze/Open-Source-Support#27]
Using `OutMan(out_path).get_element_list("reservoir")` returns nothing.

**Comment by ngerdts7** [comment]
What version are you using? There may have been an issue with the output package in 2025.2 I believe. 
I'm using 2025.3 and copy-pasting your command above works for me:
![image](https://github.com/user-attachments/assets/9908b734-8b0f-4273-a71f-d9bf57957f40)
